version: 2

sources:
  - name: dwh_car_fleet
    database: dwh_warehouse_ecs
    schema: public
    tables:
      - name: raw_car_circulating
      - name: raw_province
      - name: raw_car_spec
      - name: raw_iso_code